### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by Aviril7** [ss23/entrust-identityguard-tools#4]
I was trying to run a test with the below command

`$ ./decode-qr-uri.py 'igmobileotp://?action=secactivate&enc=VRUq6IoLWQRCMRITZEHtHUSWJiPwgu%2FN1BFyUHE5kxuHIEYoE3zmNTrAHeeUM5S3gzCnTy%2F%2Bdnbu%2FsjjQW%2BNEISx8C4ra8rLpxOl8E8w4KXHgjeBRgdvSzl%2BbzX5RYRrQlWgK8hsBT4pQYE0eFgW2TmRbzXu1Mu7XjKDcwsJLew32jQC2qyPLP8hljnv2rHwwsMfhQwgJUJYfctwLWWEDUFukEckaZ4O&v=1&mac=mhVL8BWKaishMa5%2B'`

And got the error 
`````
Traceback (most recent call last):
  File "/root/entrust-identityguard-tools/./decode-qr-uri.py", line 9, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
`````
then I installed the module(crypto) with the command `pip install crypto` then I ran the script again and it threw the same error, when I nano(file editor) the script(decode-qr-uri.py) I noticed the spelling of the word crypto begin with a upper case latter so I edit the word `Crypto` to `crypto` and try running the script again and got the same error saying

`````
Traceback (most recent call last):
  File "/root/entrust-identityguard-tools/./decode-qr-uri.py", line 9, in <module>
    from crypto.Cipher import AES
ModuleNotFoundError: No module named 'crypto.Cipher'
`````
I then edited the script again and change the word  `Cipher` to `cipher` which will be living use with `crypto.cipher`.
I then ran the script again and got the same output
````
 Traceback (most recent call last):
  File "/root/entrust-identityguard-tools/./decode-qr-uri.py", line 9, in <module>
    from crypto.cipher import AES
ModuleNotFoundError: No module named 'crypto.cipher'

`````
I then install the model crypto.cipher with the command `pip install crypto.cipher` successfully and got the below output
`````
┌──(root㉿localhost)-[~/entrust-identityguard-tools]
└─# pip install crypto.cipher
Requirement already satisfied: crypto.cipher in /usr/local/lib/python3.11/dist-packages (1)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from crypto.cipher) (2.28.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
`````

Now if you look at the output it says

Requirement already satisfied: requests in /usr/lib/python3/dist-packages `(from crypto.cipher)` (2.28.1)  

which means the module crypto.cipher exist.

Any solution?

Thanks in advance

**Comment by Aviril7** [comment]
Solution

`````
pip3 uninstall crypto 
pip3 uninstall pycrypto 
pip3 install pycryptodome
`````
